# Generated by Django 5.0.6 on 2024-06-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='calories',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='protein',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
