# Generated by Django 5.0.6 on 2024-06-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_article_calories_article_protein_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
