# Generated by Django 5.0.6 on 2024-06-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_article_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='calories',
            field=models.IntegerField(),
        ),
    ]
