# Generated by Django 5.0.6 on 2024-06-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_article_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='protein',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
