# Generated by Django 5.0.6 on 2024-07-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_article_protein'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meal',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='article',
            name='servingSize',
            field=models.TextField(default='N/A', max_length=100),
        ),
    ]
