# Generated by Django 5.0.6 on 2024-07-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_article_meal_article_servingsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='diningHall',
            field=models.IntegerField(default=1),
        ),
    ]
