# Generated by Django 5.0.6 on 2024-07-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_article_dininghall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='count',
            field=models.JSONField(default=dict),
        ),
    ]
