# Generated by Django 5.0.6 on 2024-08-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_article_carbs_article_chol_article_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sugar',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
