# Generated by Django 5.0.6 on 2024-08-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_article_sugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='line',
            field=models.TextField(default='N/A', max_length=100),
        ),
    ]
